const APP_BASE_URL = process.env.APP_BASE_URL || 'https://auditor-ai-020l.onrender.com';

export function internalEmailHTML(opts: {
  title: string;
  intro: string;
  data: Record<string, string>;
  message?: string;
  actionLabel?: string;
  actionUrl?: string;
}): string {
  const dataRows = Object.entries(opts.data)
    .map(([key, value]) => `<li><strong>${key}:</strong> ${value}</li>`)
    .join('');

  const messageHtml = opts.message ? `
    <div style="margin-top: 20px;">
      <strong>Message:</strong>
      <blockquote style="background: #f4f4f4; padding: 10px; border-left: 4px solid #ccc; margin: 10px 0;">
        ${opts.message.replace(/\n/g, '<br/>')}
      </blockquote>
    </div>
  ` : '';

  const actionHtml = opts.actionLabel && opts.actionUrl ? `
    <div style="margin-top: 20px;">
      <a href="${opts.actionUrl}" style="background: #000; color: #fff; padding: 10px 15px; text-decoration: none; border-radius: 5px;">${opts.actionLabel}</a>
    </div>
  ` : '';

  const formattedDate = new Date().toLocaleString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZone: 'Asia/Kolkata',
    timeZoneName: 'short',
  });

  return `
    <div style="font-family: system-ui, -apple-system, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
      <h2 style="border-bottom: 2px solid #000; padding-bottom: 10px;">${opts.title}</h2>
      <p style="font-size: 14px;">${opts.intro}</p>
      <ul style="list-style: none; padding: 0; font-size: 14px; background: #fafafa; padding: 15px; border-radius: 5px;">
        ${dataRows}
      </ul>
      ${messageHtml}
      ${actionHtml}
      <div style="margin-top: 30px; font-size: 12px; color: #888;">
        Generated by Auditor AI System | ${formattedDate}
      </div>
    </div>
  `;
}

export function userEmailHTML(opts: {
  greeting: string;
  bodyParagraphs: string[];
  ctaLabel?: string;
  ctaUrl?: string;
  signoff?: string;
}): string {
  const signoff = opts.signoff || "— Rishi, founder of Auditor AI";
  
  const paragraphs = opts.bodyParagraphs
    .map(p => `<p style="margin-bottom: 16px; line-height: 1.5;">${p}</p>`)
    .join('');

  const ctaHtml = opts.ctaLabel && opts.ctaUrl ? `
    <div style="margin: 30px 0;">
      <a href="${opts.ctaUrl}" style="background: #2563eb; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 8px; font-weight: bold; display: inline-block;">${opts.ctaLabel}</a>
    </div>
  ` : '';

  return `
    <div style="font-family: system-ui, -apple-system, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #1e293b;">
      <div style="margin-bottom: 30px;">
        <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="#2563eb" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
        </svg>
      </div>
      
      <h1 style="font-size: 24px; font-weight: bold; margin-bottom: 24px; color: #0f172a;">${opts.greeting}</h1>
      
      <div style="font-size: 16px; color: #334155;">
        ${paragraphs}
      </div>
      
      ${ctaHtml}
      
      <p style="margin-top: 30px; font-size: 16px; color: #334155;">
        ${signoff}
      </p>
      
      <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 40px 0 20px;" />
      
      <div style="font-size: 12px; color: #94a3b8; text-align: left; line-height: 1.5;">
        <p style="margin: 0;">Auditor AI · Audit receipts in seconds</p>
        <p style="margin: 5px 0 0;">
          <a href="${APP_BASE_URL}/privacy" style="color: #64748b; text-decoration: underline;">Privacy Policy</a> · 
          <a href="${APP_BASE_URL}/settings" style="color: #64748b; text-decoration: underline;">Manage preferences</a>
        </p>
      </div>
    </div>
  `;
}
